
@startuml
activate AddBooleanCommand

->AddBooleanCommand: execute()

activate BooleanTemplate
AddBooleanCommand -> BooleanTemplate: addGate(template, "C", and)

activate BooleanTemplate
BooleanTemplate -> BooleanTemplate: convertToIndex("C")

BooleanTemplate -> BinaryTree : insert(idx, and)
activate BinaryTree

BinaryTree --> BooleanTemplate
deactivate BinaryTree

BooleanTemplate -> BooleanTemplate : buildTopDown()
activate BooleanTemplate

BooleanTemplate --> BooleanTemplate
deactivate BooleanTemplate

BooleanTemplate --> AddBooleanCommand
deactivate BooleanTemplate

<-- AddBooleanCommand
deactivate AddBooleanCommand
@enduml
