@startuml
!include style.puml
package Gates {
    object "__:BooleanTemplate__" as State1
    object "__:OrGate__" as State2
    object "__:AndGate__" as State3
    object “__:XorGate__" as State4
    object “__:Gate__" as State5

}
object State1 {
    - BinaryTree<Gate> circuit
    + addGate(Gate gate, int index)
}
object State2 {
    int getOutput() = {return input | secondInput}
}
object State3 {
   int getOutput() = {return input & secondInput}
}
object State4 {
   int getOuput() = {return input ^ secondInput}
}

object State5 {
   int input
   void setInput()
   int getInput()
}

State1 --> State5
State5 <|-- State3
State5 <|-- State4
State5 <|-- State2
@enduml