@startuml
!include style.puml
package Gates {
    object "__:BooleanTemplate__" as Bool
    object "__:OrGate__" as Or
    object "__:AndGate__" as And
    object “__:XorGate__" as Xor
    object “__:Gate__" as Gate

}
object Bool {
    circuit
}
object Or {
}
object And {
}
object Xor {
}

object Gate {
    input
    secondInput
}

Bool --> "0..7" Gate
Gate <|-- And
Gate <|-- Xor
Gate <|-- Or
@enduml