@startuml
package Gates {
    object "__:BooleanTemplate__" as State1
    object "__:OrGate__" as State2
    object "__:AndGate__" as State3
    object “__:XorGate__" as State4
}

object State1 {
    - BinaryTree<Gate> circuit
    + addGate(Gate gate, int index)
}

object State2 {
    int B = 0
    int C = F & G = 1
    int output = B|C = 0|1 = 1
}

object State3 {
   int F = 1
   int G = 1
   int output = F & G = 1 & 1 = 1
}

object State4 {
   int H = 0
   int I = B|C
   int output = H ^ I = 1
}


State1 -- State2
State1 -- State3
State1 -- State4

@enduml