@startuml

box logic
participant ":Parser" as Parser
participant ":AddCommand" as AddCommand
end box

box model
participant ":RcTemplate" as RcTemplate
participant ":Capacitor" as Capacitor
end box

[-> Parser : parse("add parallel c 20")
activate Parser

Parser -> Parser : prepareAdd("add parallel c 20")
activate Parser

Parser -> AddCommand : AddCommand(RcTemplate,"parallel","c", 500)
activate AddCommand

Parser <-- AddCommand : add
deactivate AddCommand

Parser <-- Parser : add
deactivate Parser

[<-- Parser : add
deactivate Parser

[-> AddCommand: execute()
activate AddCommand

AddCommand -> RcTemplate : getComponent(c)
activate RcTemplate

RcTemplate -> RcTemplate : getCapacitor()
activate RcTemplate

RcTemplate <-- RcTemplate : capacitor
deactivate RcTemplate

AddCommand <-- RcTemplate : capacitor
deactivate RcTemplate

AddCommand -> AddCommand : getNewValue()
activate AddCommand

AddCommand -> Capacitor : capacitor.addParallel(20)
activate Capacitor

AddCommand <-- Capacitor : value
deactivate Capacitor

AddCommand <-- AddCommand : value
deactivate AddCommand

AddCommand -> Capacitor: capacitor.setValue(value)
activate Capacitor

AddCommand <-- Capacitor
deactivate Capacitor

[<-- AddCommand
deactivate AddCommand

@enduml
