@startuml

hide member

package Command {

class "{abstract}\nCommand" as Command
class "SummaryCommand" as Summary
class "TutorialBooleanCommand" as Tutorial

package Gates {
    class "{abstract}\nBooleanCommand" as Bool
    class "AddBooleanCommand" as Add
    class "CalculateBooleanCommand" as Calc
    class "SetBooleanCommand" as Set
    class "TemplateBooleanCommand" as Template
}
}

Bool --|> Command
Add --|> Bool
Set --|> Bool
Template --|> Bool
Calc --|> Bool
Summary --|> Command
Tutorial --|> Summary

@enduml