@startuml
box logic
participant ":Parser" as Parser
participant ":CalculateCommand" as CalculateCommand
end box

box template
participant ":Template" as Template
end box

[-> Parser : parse("calc reff")
activate Parser

Parser -> Parser : prepareCalc("calc reff")
activate Parser

Parser -> CalculateCommand : calculateCommand(template, reff)
activate CalculateCommand

Parser <-- CalculateCommand : calc
deactivate CalculateCommand

Parser <-- Parser: calc
deactivate Parser

[<-- Parser : calc
deactivate Parser

[->CalculateCommand : execute()
activate CalculateCommand

CalculateCommand -> CalculateCommand : getValue()
activate CalculateCommand

CalculateCommand -> Template : getComponent("r")
activate Template

Template -> Template : getResistor()
activate Template

Template <-- Template : value
deactivate Template

CalculateCommand <-- Template : value
deactivate Template

CalculateCommand <-- CalculateCommand : value
deactivate CalculateCommand

[<-- CalculateCommand
deactivate CalculateCommand
@enduml