@startuml
!include style.puml

hide member

package Command {

Class "{abstract}\nCommand" as Comd
Class "SummaryCommand" as Summary
Class "TutorialCircuitCommand" as Help

package "Circuit" {
Class "{abstract}\nCircuitCommand" as Circuit
Class "SetCircuitCommand" as Set
Class "AddCircuitCommand" as Add
Class "CalculateCircuitCommand" as Calc
Class "TemplateCircuitCommand" as Template
}

Help --|> Summary
Template --|> Circuit
Set --|> Circuit
Calc --|> Circuit
Add --|> Set
Summary --|> Comd
Circuit --|> Comd

@enduml