@startuml
!include style.puml

hide member

package Gate {
    class "{abstract}\nGate" as Gate
    class And
    class Or
    class Xor
    class Nand
    class Nor
    class Xnor
}

And -u-|> Gate
Or -u-|> Gate
Xor -u-|> Gate
Nand -u-|> And
Nor -u-|> Or
Xnor -u-|> Xor


@enduml