@startuml

package Model {
package Template {
    Class XYZCircuitTemplate
    Class "{abstract}\nCircuitTemplate" as CircuitTemplate
    Class BooleanTemplate
}

package Component {

    Class XYZComponent
    Class XYZLoadComponent
    Class "{abstract}\nComponent" as Component
    Class "{abstract}\nLoadComponent" as LoadComponent

}

package Gate {
    Class XYZGate
    Class "{abstract}\nGate" as Gate
}

package BinaryTree {
    Class BinaryTree<Gate>
}
}

XYZCircuitTemplate --|> CircuitTemplate

CircuitTemplate --> Component
LoadComponent --|> Component
XYZComponent --|> Component
XYZLoadComponent --|> LoadComponent

BooleanTemplate --|> BinaryTree
BooleanTemplate --> Gate
BinaryTree --> Gate

XYZGate --|> Gate

@enduml