@startuml
!include style.puml

package Gates {
    class "Gate" as Gate
    class "OrGate" as Or
}

class Gate {
    # input : int
    # output : int
    + setInput(int) : void
    + setSecondInput(int) : void
}

class Or {
    + getOutput() : int

}

Or --|> Gate
@enduml