@startuml
[-> ":SetBooleanCommand" : execute()
activate ":SetBooleanCommand"

":SetBooleanCommand" -> ":BooleanTemplate" : setInput(template, 2, 0)
activate ":BooleanTemplate"

":BooleanTemplate" -> ":BinaryTree" : getT(2)
activate ":BinaryTree"

":BinaryTree" --> ":BooleanTemplate" : gate
deactivate ":BinaryTree"

":BooleanTemplate" -> ":Gate" : setSecondInput(0)
activate ":Gate"

":Gate" --> ":BooleanTemplate"
deactivate ":Gate"

":BooleanTemplate" -> ":BooleanTemplate" : buildTopDown()
activate ":BooleanTemplate"

":BooleanTemplate" --> ":BooleanTemplate"
deactivate ":BooleanTemplate"

":BooleanTemplate" --> ":SetBooleanCommand"
deactivate ":BooleanTemplate"

[<-- ":SetBooleanCommand"
deactivate ":SetBooleanCommand"
@enduml