@startuml
[->":Parser": parse("template and")

activate ":Parser"

":Parser"-> ":BooleanParser": prepareBooleanTemplate("and")

activate ":BooleanParser"

":BooleanParser" -> ":BooleanParser": getBooleanTemplate("and")

activate ":BooleanParser"

":BooleanParser" -> ":BooleanParser": getGate("and")

activate ":BooleanParser"

":BooleanParser" --> ":BooleanParser": AndGate()

deactivate ":BooleanParser"

":BooleanParser" --> ":BooleanParser": BooleanTemplate(AndGate())

deactivate ":BooleanParser"

":BooleanParser" -> ":TemplateBooleanCommand": TemplateBooleanCommand(BooleanTemplate(AndGate()))

activate ":TemplateBooleanCommand"

":TemplateBooleanCommand" --> ":BooleanParser"
deactivate ":TemplateBooleanCommand"

":BooleanParser" --> ":Parser"
deactivate ":BooleanParser"

[<-- ":Parser"
deactivate ":Parser"
@enduml